name: test

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      foor: ${{ steps.step1.outputs.foo }}
    steps:
      - name: step1
        run: |
          echo 'foo<<EOF' >> $GITHUB_OUTPUT
          echo 'line1' >> $GITHUB_OUTPUT
          echo "line2" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: |
          echo ${{ needs.job1.outputs.foo }}